// vue-3-vite/src/App.vue
<template>
  <div>
    <div class="input">
      <label for="input">
        Details Amount:
        <input type="number" id="input" v-model.number="detailsAmount" />
      </label>
      <span>Last update: {{ lastUpdateTime ? `${lastUpdateTime}ms` : "n/a" }}</span>
      <br />
      <label for="stringInput">
        Interactive input:
        <input type="text" id="stringInput" v-model="userString" />
        <span>Result: {{ userString }}</span>
      </label>
      <br />
      <button type="button" @click="startIncrement">Start auto increment</button>
      <button type="button" @click="stopIncrement">Stop auto increment</button>
    </div>

    <div class="details">
      <MockDetail v-for="index in detailsAmount" :key="index" :index="index - 1" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, nextTick } from "vue";
import MockDetail from "./MockDetail.vue";

const detailsAmount = ref(0);
const lastUpdateTime = ref<string | null>(null);
const userString = ref("");
const startTimeRef = ref<number | null>(null);
const interval = ref(0);

function startIncrement() {
  interval.value = setInterval(() => {
    detailsAmount.value++;
  }, 1000);
}

function stopIncrement() {
  clearInterval(interval.value);
}

watch([detailsAmount, userString], async () => {
  startTimeRef.value = performance.now();
  await nextTick(); // Wait for DOM updates to complete

  const endTime = performance.now();
  lastUpdateTime.value = (endTime - startTimeRef.value).toFixed(0); // Measure the time taken for the update
});
</script>
<style>
html {
  padding: 0;
  margin: 0;
}
body {
  padding: 0;
  margin: 0;
  display: flex;
  align-items: flex-start;
  background-color: #313131;
  color: #fff2e1;
  width: 100%;
  height: 100%;
}
.input {
  height: 40px;
  width: 100%;
}
.details {
  width: 100%;
  height: 100%;
  max-width: 100vw;
  max-height: calc(100vh - 80px);
  overflow: auto;
  font-size: 4px;
  cursor: pointer;
}
.detail {
  width: 2px;
  height: 2px;
  margin: 10px;
  display: inline-block;
}

/* Add any additional styling here */
</style>

<style>
/* Vue specific */
#app {
  width: 100%;
}
</style>

// qwik/src/components/app/app.tsx
import { component$, useSignal, useTask$, $, useVisibleTask$ } from "@builder.io/qwik";
import { MockDetail } from "../mock-detail/mock-detail";

export const App = component$(() => {
  const detailsAmount = useSignal(0);
  const lastUpdateTime = useSignal<string | null>(null);
  const userString = useSignal("");
  const intervalRef = useSignal<number | null>(null);
  const startTimeRef = useSignal<number | null>(null);

  const handleChange = $((e: Event) => {
    const target = e.target as HTMLInputElement;
    detailsAmount.value = parseInt(target.value, 10) || 0;
  });

  const onStringInput = $((e: Event) => {
    const target = e.target as HTMLInputElement;
    userString.value = target.value;
  });

  const startIncrement = $(() => {
    const interval = setInterval(() => {
      detailsAmount.value++;
    }, 1000) as unknown as number;
    intervalRef.value = interval;
  });

  const stopIncrement = $(() => {
    if (intervalRef.value) clearInterval(intervalRef.value);
  });

  useTask$(({ track }) => {
    track(() => detailsAmount.value);
    track(() => userString.value);
    startTimeRef.value = performance.now();
  });

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(({ track }) => {
    track(() => detailsAmount.value);
    track(() => userString.value);
    console.log("%c⧭", "color: #733d00", lastUpdateTime.value);
    if (startTimeRef.value && performance.now() - startTimeRef.value >= 0)
      lastUpdateTime.value = `${(performance.now() - startTimeRef.value).toFixed(0)}ms`;
  });

  return (
    <div>
      <div class="input">
        <label for="input">
          Details Amount:
          <input type="number" id="input" value={detailsAmount.value} onInput$={handleChange} />
        </label>
        <span>Last update: {lastUpdateTime.value || "n/a"}</span>
        <br />

        <label for="stringInput">
          Interactive input:
          <input type="text" id="stringInput" value={userString.value} onInput$={onStringInput} />
          <span>Result: {userString.value}</span>
        </label>
        <br />
        <button type="button" onClick$={startIncrement}>
          Start auto increment
        </button>
        <button type="button" onClick$={stopIncrement}>
          Stop auto increment
        </button>
      </div>

      <div class="details">
        {Array.from({ length: detailsAmount.value }).map((_, index) => (
          <MockDetail key={index} index={index} />
        ))}
      </div>
    </div>
  );
});
