// react-18-vite/src/MockDetail.tsx
import React, { useMemo, useState } from "react";

interface MockDetailProps {
  index: number;
}

const getRandomString = (length: number) => {
  const characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
  let result = "";
  const charactersLength = characters.length;
  for (let i = 0; i < length; i++) {
    result += characters.charAt(Math.floor(Math.random() * charactersLength));
  }
  return result;
};

const getRandomColor = () => {
  const letters = "0123456789ABCDEF";
  let color = "#";
  for (let i = 0; i < 6; i++) {
    color += letters[Math.floor(Math.random() * 16)];
  }
  return color;
};

const MockDetail: React.FC<MockDetailProps> = ({ index }) => {
  const [isVisible, setIsVisible] = useState(true);
  const [clicked, setClicked] = useState(0);
  const randomString = getRandomString(5);
  const title = `${randomString}. Index: ${index}. Clicked ${clicked}`;
  const TagName = Math.random() > 0.5 ? "div" : "span";
  const backgroundColor = getRandomColor();
  const renderChild = useMemo(() => Math.random() < 0.2, []);

  function onSingleClick() {
    setClicked((click) => click + 1);
  }

  if (!isVisible) return null;

  return (
    <TagName
      title={title}
      style={{
        backgroundColor,
      }}
      className="detail"
      onDoubleClick={() => setIsVisible(false)}
      onClick={onSingleClick}
    >
      {renderChild && <div>{title}</div>}
    </TagName>
  );
};

export default MockDetail;

// angular/src/app/mock-detail/mock-detail.component.ts
import { Component, Input } from '@angular/core';
import {NgIf} from '@angular/common';

@Component({
  selector: 'app-mock-detail',
  standalone: true,
  templateUrl: './mock-detail.component.html',
  styleUrls: ['./mock-detail.component.css'],
  imports: [NgIf],
})
export class MockDetailComponent {
  @Input() index!: number;
  isVisible = true;
  clicked = 0;
  randomString = Math.random().toString(36).substring(2, 7);
  title = `${this.randomString}. Index: ${this.index}. Clicked ${this.clicked}`;
  tagName = Math.random() > 0.5 ? 'div' : 'span';
  backgroundColor = `#${Math.floor(Math.random() * 16777215).toString(16)}`;
  renderChild = Math.random() < 0.2;

  onSingleClick() {
    this.clicked++;
    this.title = `${this.randomString}. Index: ${this.index}. Clicked ${this.clicked}`;
  }

  onDoubleClick() {
    this.isVisible = false;
  }
}

<ng-container *ngIf="isVisible">
  <div *ngIf="tagName === 'div'" 
       [title]="title"
       [style.background-color]="backgroundColor"
       class="detail"
       (click)="onSingleClick()"
       (dblclick)="onDoubleClick()">
    <div *ngIf="renderChild">{{ title }}</div>
  </div>

  <span *ngIf="tagName === 'span'" 
        [title]="title"
        [style.background-color]="backgroundColor"
        class="detail"
        (click)="onSingleClick()"
        (dblclick)="onDoubleClick()">
    <div *ngIf="renderChild">{{ title }}</div>
  </span>
</ng-container>
